#!/bin/bash

## Copyright (C) 2023 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -x
set -e

torrc_file_path='/usr/local/etc/torrc.d/40_tor_control_panel.conf'
tcp_comm_file_path='/run/tor-control-panel/tor.conf'

if ! test -f "tcp_comm_file_path" ; then
  echo "$0: file '$tcp_comm_file_path' is not a file!"
  exit 1
fi

if ! test -r "$tcp_comm_file_path" ; then
  echo "$0: file '$tcp_comm_file_path' is not readable!"
  exit 1
fi

mkdir --parents --verbose '/usr/local/etc/torrc.d'

## Do not move the original file, as the creator may have set a lock on it,
## which could interfere with other users of the file. Copy and delete the
## original instead.
cp --verbose "$tcp_comm_file_path" "$torrc_file_path"
safe-rm "$tcp_comm_file_path"

## We set 40_tor_control_panel.conf to chmod 644
## so that only root can write and read, others can only read,
## which prevents the edit by normal user.
chmod --verbose 644 "$torrc_file_path"

exit 0
